buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.0.+', changing: true
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

version = '1.2.0'
group = 'net.petitboxer.betterdrop'
archivesBaseName = 'betterdrop'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty('java.version')}, JVM: ${System.getProperty('java.vm.version')} (${System.getProperty('java.vendor')}), Arch: ${System.getProperty('os.arch')}"

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            // Force la JVM ModLauncher à charger la config Mixin en dev
            property 'mixin.config', 'betterdrop.mixins.json'

            mods {
                betterdrop {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.config', 'betterdrop.mixins.json'

            mods {
                betterdrop {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    // Déclare le fichier de configuration Mixin au build
    add sourceSets.main, 'betterdrop.mixins.refmap.json'
    config 'betterdrop.mixins.json'
}

sourceSets.main.resources { srcDir 'src/main/resources' }

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.1.3'

    // Dépendance d'annotation pour la génération automatique du refmap Mixin
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    // Permet de gérer les doublons sans faire planter le build
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    var replaceProperties = [
            minecraft_version: '1.20.1',
            mod_id: 'betterdrop',
            mod_name: 'BetterDrop',
            mod_version: version
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}