modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="betterdrop"
version="1.0.1"
displayName="BetterDrop"
authors="PetitBoxer"
description='''
Better Drop is a Quality of Life (QoL) mod that completely overhauls how item entities behave on the ground in Minecraft.

* Features:
Manual Pickup: Items no longer automatically enter your inventory when walking over them.
'''
Mixins = ["betterdrop.mixins.json"]